{% set name = "set-calibration" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f9064261af306176a2e731d34d661921ac6ec21ed86a5da6df838a1d78b4a294

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - set_calibration
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/set-calibration
  summary: A tool allowing to modify the calibration (physical units) of images
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MontpellierRessourcesImagerie/set-calibration

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
