{% set name = "set-calibration" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/set-calibration-{{ version }}.tar.gz
  sha256: 7b36e4aad0248e0fdcc00c1e550f8b3c1b6688d7816781c7b5ef43a1c513f7eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - set_calibration
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/set-calibration
  summary: A tool allowing to modify the calibration (physical units) of images
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MontpellierRessourcesImagerie/set-calibration

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
